USE DB_BTS;
GO



CREATE TABLE [Admin]
	(
		[AdminID] INTEGER IDENTITY(1,1),
		[PersonID] INTEGER NOT NULL,
		CONSTRAINT PK_AdminID PRIMARY KEY (AdminID),
		CONSTRAINT FK_PersonID FOREIGN KEY (PersonID) REFERENCES Person(PersonID)
	);