USE DB_BTS;

CREATE TABLE [PROJECT]
	(
		[ProjectID] INTEGER IDENTITY(1, 1) NOT NULL,
		[Name] VARCHAR(50) NOT NULL,
		[Desc] VARCHAR(100),
		[CreationDate] DATE NOT NULL,
		CONSTRAINT PK_ProjectID PRIMARY KEY (ProjectID)
	);
