USE DB_BTS;

CREATE TABLE [REPORT_STATUS_TYPE] 
	(
		[StatusID] INTEGER IDENTITY(1, 1) NOT NULL,
		[Name] VARCHAR(20) NOT NULL,
		[Desc] VARCHAR(200) NOT NULL

		CONSTRAINT PK_StatusID PRIMARY KEY (StatusID)
	);