USE DB_BTS;

CREATE TABLE [REPORT_COMMENTS] 
	(
		[CommentsID] INTEGER IDENTITY(1, 1),
		[PersonID] INTEGER NOT NULL,
		[ReportID] INTEGER NOT NULL,
		[Comment] VARCHAR(200) NOT NULL,
		[DateCommented] DATETIME NOT NULL,

		CONSTRAINT PK_CommentID PRIMARY KEY (CommentsID),
		CONSTRAINT FK_Report_Comments_Person FOREIGN KEY(PersonID) REFERENCES [PERSON](PersonID),
		CONSTRAINT FK_Report_Comments_Report_Info FOREIGN KEY(ReportID) REFERENCES [REPORT_INFO](ReportID)
	
	);