USE DB_BTS;

CREATE TABLE [REPORT_INFO]
	(	
		[ReportID] INTEGER IDENTITY(1, 1) NOT NULL,
		[ReportTypeID] INTEGER NOT NULL,
		[StatusID] INTEGER NOT NULL,
		[ReportTitle] VARCHAR(50) NOT NULL,
		[Desription] VARCHAR(200) NOT NULL,
		[DateReported] DATETIME NOT NULL,
		[PersonID] INTEGER NOT NULL,
		[Priority] VARCHAR(10) NOT NULL,
		[LastReportStatusDate] DATETIME,

		CONSTRAINT PK_ReportID PRIMARY KEY (ReportID),
		CONSTRAINT FK_ReportTypeID FOREIGN KEY (ReportTypeID) REFERENCES [REPORT_TYPE](ReportTypeID),
		CONSTRAINT FK_Report_Info_PersonID FOREIGN KEY (PersonID) REFERENCES [PERSON](PersonID),
		CONSTRAINT FK_Report_Info_Report_Status_Type FOREIGN KEY (StatusID) REFERENCES [REPORT_STATUS_TYPE](StatusID)
	);