USE DB_BTS;

CREATE TABLE [User]
	(
		[UserID] INTEGER IDENTITY(1,1) NOT NULL,
		[PersonID] INTEGER NOT NULL,
		[AdminID] INTEGER NOT NULL,
		[TitleID] INTEGER NOT NULL,
		CONSTRAINT PK_UserID PRIMARY KEY (UserID),
		CONSTRAINT FK_User_PersonID FOREIGN KEY (PersonID) REFERENCES Person(PersonID),
		CONSTRAINT FK_User_AdminID FOREIGN KEY (AdminID) REFERENCES Admin(AdminID),
		CONSTRAINT FK_User_TitleID FOREIGN KEY (TitleID) REFERENCES User_Title(TitleID)
	);