USE DB_BTS;

CREATE TABLE [WATCHER] 
	(
		[WatcherID] INTEGER IDENTITY(1, 1),
		[PersonID] INTEGER NOT NULL,
		[ReportID] INTEGER NOT NULL,
		
		CONSTRAINT PK_WatcherID PRIMARY KEY ( WatcherID),
		CONSTRAINT FK_ProjectID FOREIGN KEY (ReportID) REFERENCES [REPORT_INFO](ReportID),
		CONSTRAINT FK_PersonID FOREIGN KEY (PersonID) REFERENCES [PERSON](PersonID)
	);